class ParsePriorParamCollection {
  final String itemId;
  final String name;
  final String type;
  final int coinAmount;
  final String price;
  final String description;
  final String locale;
  final String category;

  const ParsePriorParamCollection({
    required this.itemId,
    required this.name,
    required this.type,
    required this.coinAmount,
    required this.price,
    required this.description,
    required this.locale,
    required this.category,
  });
}

const List<ParsePriorParamCollection> shopInventory = <ParsePriorParamCollection>[
  ParsePriorParamCollection(
    itemId: 'strim1000',
    name: 'Strim Package',
    type: 'basic',
    coinAmount: 100,
    price: '0.99',
    description: 'Strim Package',
    locale: 'en_US',
    category: 'basic',
  ),
  ParsePriorParamCollection(
    itemId: 'strim1001',
    name: 'Strim Package 1',
    type: 'basic',
    coinAmount: 500,
    price: '4.99',
    description: 'Strim Package 1',
    locale: 'en_US',
    category: 'basic',
  ),
  ParsePriorParamCollection(
    itemId: 'strim1002',
    name: 'Strim Package 2',
    type: 'basic',
    coinAmount: 1200,
    price: '9.99',
    description: 'Strim Package 2',
    locale: 'en_US',
    category: 'basic',
  ),
  ParsePriorParamCollection(
    itemId: 'strim1003',
    name: 'Strim Package 3',
    type: 'basic',
    coinAmount: 2500,
    price: '19.99',
    description: 'Strim Package 3',
    locale: 'en_US',
    category: 'basic',
  ),
  ParsePriorParamCollection(
    itemId: 'strim1004',
    name: 'Strim Package 4',
    type: 'basic',
    coinAmount: 7000,
    price: '49.99',
    description: 'Strim Package 4',
    locale: 'en_US',
    category: 'basic',
  ),
  ParsePriorParamCollection(
    itemId: 'strim1005',
    name: 'Strim Package 5',
    type: 'basic',
    coinAmount: 15000,
    price: '99.99',
    description: 'Strim Package 5',
    locale: 'en_US',
    category: 'basic',
  ),
  ParsePriorParamCollection(
    itemId: 'strim1006',
    name: 'Strim Package 1 (Big Off)',
    type: 'basic',
    coinAmount: 500,
    price: '1.99',
    description: 'Strim Package 1 (Big Off)',
    locale: 'en_US',
    category: 'promo',
  ),
  ParsePriorParamCollection(
    itemId: 'strim1007',
    name: 'Strim Package 2 (Big Off)',
    type: 'basic',
    coinAmount: 1200,
    price: '4.99',
    description: 'Strim Package 2 (Big Off)',
    locale: 'en_US',
    category: 'promo',
  ),
  ParsePriorParamCollection(
    itemId: 'strim1008',
    name: 'Strim Package 3 (Big Off)',
    type: 'basic',
    coinAmount: 2500,
    price: '11.99',
    description: 'Strim Package 3 (Big Off)',
    locale: 'en_US',
    category: 'promo',
  ),
  ParsePriorParamCollection(
    itemId: 'strim1009',
    name: 'Strim Package 4 (Big Off)',
    type: 'basic',
    coinAmount: 7000,
    price: '34.99',
    description: 'Strim Package 4 (Big Off)',
    locale: 'en_US',
    category: 'promo',
  ),
  ParsePriorParamCollection(
    itemId: 'strim1010',
    name: 'Strim Package 5 (Big Off)',
    type: 'basic',
    coinAmount: 15000,
    price: '79.99',
    description: 'Strim Package 5 (Big Off)',
    locale: 'en_US',
    category: 'promo',
  ),
  ParsePriorParamCollection(
    itemId: 'strim1011',
    name: 'Strim 1MonthMember',
    type: 'subscription',
    coinAmount: 800,
    price: '3.99',
    description: 'Strim 1MonthMember',
    locale: 'en_US',
    category: 'vip',
  ),
  ParsePriorParamCollection(
    itemId: 'strim1012',
    name: 'Strim LifetimeMember',
    type: 'basic',
    coinAmount: 1200,
    price: '6.99',
    description: 'Strim LifetimeMember',
    locale: 'en_US',
    category: 'vip',
  ),
];
