import 'package:flutter/foundation.dart';
import '../models/astro_target.dart';
import '../models/session_log.dart';

class DataService extends ChangeNotifier {
  final List<AstroTarget> _targets = [
    // 1. M42 Orion Nebula
    const AstroTarget(
      id: 'm42',
      name: 'M42 Orion Nebula',
      description:
          'The Orion Nebula is a diffuse nebula situated in the Milky Way, being south of Orion\'s Belt in the constellation of Orion. It is one of the brightest nebulae and is visible to the naked eye in the night sky.',
      imageUrl: 'assets/4711772697526_.pic_hd.jpg',
      palette: 'RGB',
      integrationHours: 4.5,
      focalLength: 350,
      cameraModel: 'ASI533MC',
      constellation: 'Orion',
      distance: '1,344 ly',
      apparentMagnitude: '+4.0',
      rightAscension: '05h 35m 17s',
      declination: '-05° 23′ 28″',
      bestSeason: 'Winter',
      type: 'Diffuse Nebula',
      size: '65 x 60 arcmin',
      discoveryInfo: 'Discovered by Nicholas-Claude Fabri de Peiresc in 1610',
    ),
    // 2. M31 Andromeda Galaxy
    const AstroTarget(
      id: 'm31',
      name: 'M31 Andromeda',
      description:
          'The Andromeda Galaxy is a barred spiral galaxy approximately 2.5 million light-years from Earth and the nearest major galaxy to the Milky Way. It is expected to collide with the Milky Way in about 4.5 billion years.',
      imageUrl: 'assets/4721772697526_.pic_hd.jpg',
      palette: 'LRGB',
      integrationHours: 12.0,
      focalLength: 420,
      cameraModel: 'ASI2600MM',
      constellation: 'Andromeda',
      distance: '2.537 Mly',
      apparentMagnitude: '+3.44',
      rightAscension: '00h 42m 44s',
      declination: '+41° 16′ 09″',
      bestSeason: 'Autumn',
      type: 'Spiral Galaxy',
      size: '190 x 60 arcmin',
      discoveryInfo: 'First described by Abd al-Rahman al-Sufi around 964',
    ),
    // 3. NGC 2244 Rosette Nebula
    const AstroTarget(
      id: 'ngc2244',
      name: 'Rosette Nebula',
      description:
          'The Rosette Nebula is a large spherical H II region located near one end of a giant molecular cloud in the Monoceros region of the Milky Way Galaxy. The open cluster NGC 2244 is closely associated with the nebulosity.',
      imageUrl: 'assets/4731772697527_.pic_hd.jpg',
      palette: 'SHO',
      integrationHours: 18.5,
      focalLength: 600,
      cameraModel: 'ASI6200MM',
      constellation: 'Monoceros',
      distance: '5,000 ly',
      apparentMagnitude: '+9.0',
      rightAscension: '06h 32m 19s',
      declination: '+04° 51′ 21″',
      bestSeason: 'Winter',
      type: 'Emission Nebula',
      size: '1.3°',
      discoveryInfo: 'Cluster discovered by John Flamsteed in 1690',
    ),
    // 4. IC 434 Horsehead Nebula
    const AstroTarget(
      id: 'ic434',
      name: 'Horsehead Nebula',
      description:
          'The Horsehead Nebula is a small dark nebula in the constellation Orion. The nebula is located just to the south of Alnitak, the easternmost star of Orion\'s Belt, and is part of the much larger Orion Molecular Cloud Complex.',
      imageUrl: 'assets/4741772697528_.pic_hd.jpg',
      palette: 'Ha-RGB',
      integrationHours: 8.2,
      focalLength: 900,
      cameraModel: 'ASI294MM',
      constellation: 'Orion',
      distance: '1,375 ly',
      apparentMagnitude: '+6.8',
      rightAscension: '05h 40m 59s',
      declination: '-02° 27′ 30″',
      bestSeason: 'Winter',
      type: 'Dark Nebula',
      size: '8 x 6 arcmin',
      discoveryInfo: 'Discovered by Williamina Fleming in 1888',
    ),
    // 5. M45 Pleiades
    const AstroTarget(
      id: 'm45',
      name: 'M45 Pleiades',
      description:
          'The Pleiades, also known as the Seven Sisters and Messier 45, are an open star cluster containing middle-aged, B-type stars in the north-west of the constellation Taurus.',
      imageUrl: 'assets/4751772697529_.pic_hd.jpg',
      palette: 'RGB',
      integrationHours: 6.0,
      focalLength: 400,
      cameraModel: 'ASI071MC',
      constellation: 'Taurus',
      distance: '444 ly',
      apparentMagnitude: '+1.6',
      rightAscension: '03h 47m 24s',
      declination: '+24° 07′ 00″',
      bestSeason: 'Winter',
      type: 'Open Cluster',
      size: '110 arcmin',
      discoveryInfo: 'Known since antiquity',
    ),
    // 6. M33 Triangulum Galaxy
    const AstroTarget(
      id: 'm33',
      name: 'M33 Triangulum',
      description:
          'The Triangulum Galaxy is a spiral galaxy 2.73 million light-years from Earth in the constellation Triangulum. It is catalogued as Messier 33 or NGC 598.',
      imageUrl: 'assets/4761772697530_.pic_hd.jpg',
      palette: 'LRGB',
      integrationHours: 15.4,
      focalLength: 530,
      cameraModel: 'ASI1600MM',
      constellation: 'Triangulum',
      distance: '2.73 Mly',
      apparentMagnitude: '+5.72',
      rightAscension: '01h 33m 50s',
      declination: '+30° 39′ 36″',
      bestSeason: 'Autumn',
      type: 'Spiral Galaxy',
      size: '70.8 x 41.7 arcmin',
      discoveryInfo: 'Discovered by Giovanni Battista Hodierna before 1654',
    ),
    // 7. M16 Eagle Nebula
    const AstroTarget(
      id: 'm16',
      name: 'M16 Eagle Nebula',
      description:
          'The Eagle Nebula is a young open cluster of stars in the constellation Serpens, discovered by Jean-Philippe de Chéseaux in 1745-46. It contains several active star-forming gas and dust regions, including the "Pillars of Creation".',
      imageUrl: 'assets/4771772697532_.pic_hd.jpg',
      palette: 'SHO',
      integrationHours: 22.0,
      focalLength: 1200,
      cameraModel: 'ASI2600MM',
      constellation: 'Serpens',
      distance: '5,700 ly',
      apparentMagnitude: '+6.0',
      rightAscension: '18h 18m 48s',
      declination: '-13° 49′ 00″',
      bestSeason: 'Summer',
      type: 'Emission Nebula',
      size: '7 x 7 arcmin',
      discoveryInfo: 'Discovered by Jean-Philippe de Chéseaux in 1745',
    ),
    // 8. M8 Lagoon Nebula
    const AstroTarget(
      id: 'm8',
      name: 'M8 Lagoon Nebula',
      description:
          'The Lagoon Nebula is a giant interstellar cloud in the constellation Sagittarius. It is classified as an emission nebula and as an H II region.',
      imageUrl: 'assets/4781772697532_.pic_hd.jpg',
      palette: 'HOO',
      integrationHours: 5.5,
      focalLength: 700,
      cameraModel: 'ASI533MC',
      constellation: 'Sagittarius',
      distance: '4,100 ly',
      apparentMagnitude: '+6.0',
      rightAscension: '18h 03m 37s',
      declination: '-24° 23′ 12″',
      bestSeason: 'Summer',
      type: 'Emission Nebula',
      size: '90 x 40 arcmin',
      discoveryInfo: 'Discovered by Giovanni Hodierna before 1654',
    ),
    // 9. M20 Trifid Nebula
    const AstroTarget(
      id: 'm20',
      name: 'M20 Trifid Nebula',
      description:
          'The Trifid Nebula is an H II region in the north-west of Sagittarius in a star-forming region in the Scutum-Centaurus Arm of the Milky Way.',
      imageUrl: 'assets/4791772697533_.pic_hd.jpg',
      palette: 'RGB',
      integrationHours: 7.0,
      focalLength: 800,
      cameraModel: 'ASI294MC',
      constellation: 'Sagittarius',
      distance: '5,200 ly',
      apparentMagnitude: '+6.3',
      rightAscension: '18h 02m 23s',
      declination: '-23° 01′ 48″',
      bestSeason: 'Summer',
      type: 'Emission / Reflection / Dark Nebula',
      size: '28 arcmin',
      discoveryInfo: 'Discovered by Charles Messier in 1764',
    ),
    // 10. NGC 7000 North America Nebula
    const AstroTarget(
      id: 'ngc7000',
      name: 'North America Nebula',
      description:
          'The North America Nebula is an emission nebula in the constellation Cygnus, close to Deneb. The remarkable shape of the nebula resembles that of the continent of North America.',
      imageUrl: 'assets/4801772697535_.pic_hd.jpg',
      palette: 'SHO',
      integrationHours: 10.5,
      focalLength: 300,
      cameraModel: 'ASI183MM',
      constellation: 'Cygnus',
      distance: '2,590 ly',
      apparentMagnitude: '+4.0',
      rightAscension: '20h 58m 47s',
      declination: '+44° 19′ 48″',
      bestSeason: 'Summer',
      type: 'Emission Nebula',
      size: '120 x 100 arcmin',
      discoveryInfo: 'Discovered by William Herschel in 1786',
    ),
    // 11. M101 Pinwheel Galaxy
    const AstroTarget(
      id: 'm101',
      name: 'M101 Pinwheel',
      description:
          'The Pinwheel Galaxy is a face-on spiral galaxy distanced 21 million light-years away from Earth in the constellation Ursa Major.',
      imageUrl: 'assets/4811772697535_.pic_hd.jpg',
      palette: 'LRGB',
      integrationHours: 25.0,
      focalLength: 1000,
      cameraModel: 'ASI2600MM',
      constellation: 'Ursa Major',
      distance: '20.87 Mly',
      apparentMagnitude: '+7.86',
      rightAscension: '14h 03m 12s',
      declination: '+54° 20′ 57″',
      bestSeason: 'Spring',
      type: 'Spiral Galaxy',
      size: '28.8 x 26.9 arcmin',
      discoveryInfo: 'Discovered by Pierre Méchain in 1781',
    ),
    // 12. M51 Whirlpool Galaxy
    const AstroTarget(
      id: 'm51',
      name: 'M51 Whirlpool',
      description:
          'The Whirlpool Galaxy is an interacting grand-design spiral galaxy with a Seyfert 2 active galactic nucleus. It lies in the constellation Canes Venatici.',
      imageUrl: 'assets/4821772697536_.pic_hd.jpg',
      palette: 'LRGB',
      integrationHours: 19.5,
      focalLength: 1500,
      cameraModel: 'ASI6200MM',
      constellation: 'Canes Venatici',
      distance: '23.48 Mly',
      apparentMagnitude: '+8.4',
      rightAscension: '13h 29m 52s',
      declination: '+47° 11′ 43″',
      bestSeason: 'Spring',
      type: 'Spiral Galaxy',
      size: '11.2 x 6.9 arcmin',
      discoveryInfo: 'Discovered by Charles Messier in 1773',
    ),
    // 13. M81 Bode's Galaxy
    const AstroTarget(
      id: 'm81',
      name: 'M81 Bode\'s Galaxy',
      description:
          'Messier 81 is a spiral galaxy about 12 million light-years away, with a diameter of 90,000 light-years, in the constellation Ursa Major.',
      imageUrl: 'assets/4831772697538_.pic_hd.jpg',
      palette: 'LRGB',
      integrationHours: 14.0,
      focalLength: 850,
      cameraModel: 'ASI294MM',
      constellation: 'Ursa Major',
      distance: '11.74 Mly',
      apparentMagnitude: '+6.94',
      rightAscension: '09h 55m 33s',
      declination: '+69° 03′ 55″',
      bestSeason: 'Spring',
      type: 'Spiral Galaxy',
      size: '26.9 x 14.1 arcmin',
      discoveryInfo: 'Discovered by Johann Elert Bode in 1774',
    ),
    // 14. M13 Hercules Cluster
    const AstroTarget(
      id: 'm13',
      name: 'M13 Hercules Cluster',
      description:
          'The Great Globular Cluster in Hercules is a globular cluster of about several hundred thousand stars in the constellation of Hercules.',
      imageUrl: 'assets/4841772697539_.pic_hd.jpg',
      palette: 'RGB',
      integrationHours: 2.0,
      focalLength: 2000,
      cameraModel: 'ASI174MM',
      constellation: 'Hercules',
      distance: '22,200 ly',
      apparentMagnitude: '+5.8',
      rightAscension: '16h 41m 41s',
      declination: '+36° 27′ 37″',
      bestSeason: 'Summer',
      type: 'Globular Cluster',
      size: '20 arcmin',
      discoveryInfo: 'Discovered by Edmond Halley in 1714',
    ),
    // 15. NGC 6960 Veil Nebula
    const AstroTarget(
      id: 'ngc6960',
      name: 'Veil Nebula',
      description:
          'The Veil Nebula is a cloud of heated and ionized gas and dust in the constellation Cygnus. It constitutes the visible portions of the Cygnus Loop, a supernova remnant.',
      imageUrl: 'assets/4851772697540_.pic_hd.jpg',
      palette: 'HOO',
      integrationHours: 16.0,
      focalLength: 450,
      cameraModel: 'ASI2600MC',
      constellation: 'Cygnus',
      distance: '2,400 ly',
      apparentMagnitude: '+7.0',
      rightAscension: '20h 45m 38s',
      declination: '+30° 42′ 30″',
      bestSeason: 'Summer',
      type: 'Supernova Remnant',
      size: '3°',
      discoveryInfo: 'Discovered by William Herschel in 1784',
    ),
    // 16. IC 1805 Heart Nebula
    const AstroTarget(
      id: 'ic1805',
      name: 'Heart Nebula',
      description:
          'The Heart Nebula is an emission nebula, 7500 light years away from Earth and located in the Perseus Arm of the Galaxy in the constellation Cassiopeia.',
      imageUrl: 'assets/4861772697541_.pic_hd.jpg',
      palette: 'SHO',
      integrationHours: 28.0,
      focalLength: 350,
      cameraModel: 'ASI6200MM',
      constellation: 'Cassiopeia',
      distance: '7,500 ly',
      apparentMagnitude: '+6.5',
      rightAscension: '02h 33m 22s',
      declination: '+61° 26′ 36″',
      bestSeason: 'Autumn',
      type: 'Emission Nebula',
      size: '150 x 150 arcmin',
      discoveryInfo: 'Discovered by William Herschel in 1787',
    ),
    // 17. IC 1848 Soul Nebula
    const AstroTarget(
      id: 'ic1848',
      name: 'Soul Nebula',
      description:
          'The Soul Nebula is an emission nebula located in Cassiopeia. Several small open clusters are embedded in the nebula: CR 34, 632, and 634.',
      imageUrl: 'assets/4871772697542_.pic_hd.jpg',
      palette: 'SHO',
      integrationHours: 24.5,
      focalLength: 400,
      cameraModel: 'ASI2600MM',
      constellation: 'Cassiopeia',
      distance: '7,500 ly',
      apparentMagnitude: '+6.5',
      rightAscension: '02h 51m 18s',
      declination: '+60° 26′ 54″',
      bestSeason: 'Autumn',
      type: 'Emission Nebula',
      size: '100 x 60 arcmin',
      discoveryInfo: 'Discovered by William Herschel in 1787',
    ),
    // 18. M27 Dumbbell Nebula
    const AstroTarget(
      id: 'm27',
      name: 'M27 Dumbbell',
      description:
          'The Dumbbell Nebula was the first planetary nebula to be discovered. It is located in the constellation Vulpecula, at a distance of about 1,360 light-years.',
      imageUrl: 'assets/4881772697543_.pic_hd.jpg',
      palette: 'HOO',
      integrationHours: 9.0,
      focalLength: 1000,
      cameraModel: 'ASI533MC',
      constellation: 'Vulpecula',
      distance: '1,360 ly',
      apparentMagnitude: '+7.5',
      rightAscension: '19h 59m 36s',
      declination: '+22° 43′ 16″',
      bestSeason: 'Summer',
      type: 'Planetary Nebula',
      size: '8 x 5.6 arcmin',
      discoveryInfo: 'Discovered by Charles Messier in 1764',
    ),
    // 19. M57 Ring Nebula
    const AstroTarget(
      id: 'm57',
      name: 'M57 Ring Nebula',
      description:
          'The Ring Nebula is a planetary nebula in the northern constellation of Lyra. Such a nebula is formed when a star, during the last stages of its evolution before becoming a white dwarf, expels a vast luminous envelope of ionized gas.',
      imageUrl: 'assets/4891772697544_.pic_hd.jpg',
      palette: 'RGB',
      integrationHours: 5.0,
      focalLength: 2500,
      cameraModel: 'ASI462MC',
      constellation: 'Lyra',
      distance: '2,567 ly',
      apparentMagnitude: '+8.8',
      rightAscension: '18h 53m 35s',
      declination: '+33° 01′ 45″',
      bestSeason: 'Summer',
      type: 'Planetary Nebula',
      size: '1.4 x 1.0 arcmin',
      discoveryInfo: 'Discovered by Antoine Darquier de Pellepoix in 1779',
    ),
    // 20. NGC 1499 California Nebula
    const AstroTarget(
      id: 'ngc1499',
      name: 'California Nebula',
      description:
          'The California Nebula is an emission nebula located in the constellation Perseus. Its fluorescence is due to excitation of the Hβ line in the nebula by the nearby prodigiously energetic O7 star, Xi Persei.',
      imageUrl: 'assets/4901772697546_.pic_hd.jpg',
      palette: 'Ha',
      integrationHours: 11.5,
      focalLength: 200,
      cameraModel: 'ASI1600MM',
      constellation: 'Perseus',
      distance: '1,000 ly',
      apparentMagnitude: '+6.0',
      rightAscension: '04h 03m 18s',
      declination: '+36° 25′ 18″',
      bestSeason: 'Winter',
      type: 'Emission Nebula',
      size: '145 x 40 arcmin',
      discoveryInfo: 'Discovered by E. E. Barnard in 1884',
    ),
    // 21. M64 Black Eye Galaxy
    const AstroTarget(
      id: 'm64',
      name: 'M64 Black Eye',
      description:
          'The Black Eye Galaxy is a relatively isolated spiral galaxy 17 million light-years away in the mildly northern constellation of Coma Berenices.',
      imageUrl: 'assets/4911772697547_.pic_hd.jpg',
      palette: 'LRGB',
      integrationHours: 13.0,
      focalLength: 1200,
      cameraModel: 'ASI294MM',
      constellation: 'Coma Berenices',
      distance: '17 Mly',
      apparentMagnitude: '+9.36',
      rightAscension: '12h 56m 43s',
      declination: '+21° 40′ 58″',
      bestSeason: 'Spring',
      type: 'Spiral Galaxy',
      size: '10.7 x 5.1 arcmin',
      discoveryInfo: 'Discovered by Edward Pigott in 1779',
    ),
    // 22. M104 Sombrero Galaxy
    const AstroTarget(
      id: 'm104',
      name: 'M104 Sombrero',
      description:
          'The Sombrero Galaxy is a spiral galaxy in the constellation borders of Virgo and Corvus, being about 9.55 megaparsecs from Earth.',
      imageUrl: 'assets/4921772697548_.pic_hd.jpg',
      palette: 'LRGB',
      integrationHours: 18.0,
      focalLength: 1600,
      cameraModel: 'ASI2600MM',
      constellation: 'Virgo',
      distance: '29.3 Mly',
      apparentMagnitude: '+8.0',
      rightAscension: '12h 39m 59s',
      declination: '-11° 37′ 23″',
      bestSeason: 'Spring',
      type: 'Spiral Galaxy',
      size: '8.7 x 3.5 arcmin',
      discoveryInfo: 'Discovered by Pierre Méchain in 1781',
    ),
    // 23. NGC 253 Sculptor Galaxy
    const AstroTarget(
      id: 'ngc253',
      name: 'Sculptor Galaxy',
      description:
          'The Sculptor Galaxy is an intermediate spiral galaxy in the constellation Sculptor. It is a starburst galaxy, which means that it is currently undergoing a period of intense star formation.',
      imageUrl: 'assets/4931772697549_.pic_hd.jpg',
      palette: 'LRGB',
      integrationHours: 20.5,
      focalLength: 800,
      cameraModel: 'ASI6200MM',
      constellation: 'Sculptor',
      distance: '11.4 Mly',
      apparentMagnitude: '+8.0',
      rightAscension: '00h 47m 33s',
      declination: '-25° 17′ 18″',
      bestSeason: 'Autumn',
      type: 'Intermediate Spiral Galaxy',
      size: '27.5 x 6.8 arcmin',
      discoveryInfo: 'Discovered by Caroline Herschel in 1783',
    ),
  ];

  List<AstroTarget> get targets => _targets;

  void removeTarget(String id) {
    _targets.removeWhere((target) => target.id == id);
    notifyListeners();
  }

  // Session Logs
  final List<SessionLog> _logs = [];

  List<SessionLog> get logs => List.unmodifiable(_logs);

  void addLog(SessionLog log) {
    _logs.add(log);
    notifyListeners();
  }

  void removeLog(SessionLog log) {
    _logs.remove(log);
    notifyListeners();
  }
}
