import '../models/poem.dart';
import '../models/author.dart';

class MockDataService {
  // 20位诗人的完整数据
  static final Map<String, Author> _authors = {
    'author1': Author(
      id: 'author1',
      name: 'Emily Whitmore',
      philosophy: 'Poetry is the whisper of the soul in a world too loud to listen. I write to remember what silence sounds like and to celebrate the quiet moments that shape our lives.',
      avatarUrl: 'assets/tx/17921765208762_.pic_hd.jpg',
      worksCount: 3,
      appreciationCount: 2340,
      collections: ['Whispers of Dawn', 'Silent Echoes'],
      isPro: true,
      location: 'Portland',
      genre: 'Contemporary',
    ),
    'author2': Author(
      id: 'author2',
      name: 'Marcus Chen',
      philosophy: 'Every poem is a bridge between what was and what could be. I build these bridges with words, connecting hearts across time and space.',
      avatarUrl: 'assets/tx/17931765208763_.pic_hd.jpg',
      worksCount: 2,
      appreciationCount: 1890,
      collections: ['Bridges', 'Between Worlds'],
      isPro: false,
      location: 'San Francisco',
      genre: 'Modern',
    ),
    'author3': Author(
      id: 'author3',
      name: 'Sofia Ramirez',
      philosophy: 'In the dance of words, I find freedom. Poetry is my celebration of life, my rebellion against the ordinary, my song of joy.',
      avatarUrl: 'assets/tx/17941765208763_.pic_hd.jpg',
      worksCount: 3,
      appreciationCount: 3120,
      collections: ['Dance of Words', 'Celebration'],
      isPro: true,
      location: 'Barcelona',
      genre: 'Experimental',
    ),
    'author4': Author(
      id: 'author4',
      name: 'James O\'Connor',
      philosophy: 'The earth speaks in verses of growth and renewal. I am merely its translator, capturing the language of wind, stone, and the eternal cycle of seasons.',
      avatarUrl: 'assets/tx/17951765208764_.pic_hd.jpg',
      worksCount: 2,
      appreciationCount: 1560,
      collections: ['Earth Songs'],
      isPro: false,
      location: 'Dublin',
      genre: 'Nature Poetry',
    ),
    'author5': Author(
      id: 'author5',
      name: 'Aisha Patel',
      philosophy: 'Poetry is the art of saying everything by saying almost nothing. In brevity, I find infinity. In simplicity, I discover profound truth.',
      avatarUrl: 'assets/tx/17961765208765_.pic_hd.jpg',
      worksCount: 3,
      appreciationCount: 2780,
      collections: ['Infinite Brevity', 'Haiku Dreams'],
      isPro: true,
      location: 'Mumbai',
      genre: 'Minimalist',
    ),
    'author6': Author(
      id: 'author6',
      name: 'Lucas Bergström',
      philosophy: 'Winter taught me that beauty exists in stillness. My poems are frozen moments of wonder, waiting to warm hearts and inspire hope.',
      avatarUrl: 'assets/tx/17971765208766_.pic_hd.jpg',
      worksCount: 2,
      appreciationCount: 1920,
      collections: ['Frozen Moments'],
      isPro: false,
      location: 'Stockholm',
      genre: 'Nordic Poetry',
    ),
    'author7': Author(
      id: 'author7',
      name: 'Isabella Rossi',
      philosophy: 'Love is the greatest poem ever written. I write to celebrate connection, to honor relationships, and to remind us that we are never truly alone.',
      avatarUrl: 'assets/tx/17981765208767_.pic_hd.jpg',
      worksCount: 3,
      appreciationCount: 4230,
      collections: ['Love Letters', 'The Heart Speaks'],
      isPro: true,
      location: 'Rome',
      genre: 'Romantic',
    ),
    'author8': Author(
      id: 'author8',
      name: 'Kenji Tanaka',
      philosophy: 'The city breathes in haiku. Three lines to capture a thousand neon lights, a million stories, and the beautiful chaos of urban life.',
      avatarUrl: 'assets/tx/17991765208768_.pic_hd.jpg',
      worksCount: 2,
      appreciationCount: 2100,
      collections: ['Urban Haiku'],
      isPro: true,
      location: 'Tokyo',
      genre: 'Urban Poetry',
    ),
    'author9': Author(
      id: 'author9',
      name: 'Amara Okafor',
      philosophy: 'My ancestors spoke in proverbs. I speak in poems. The rhythm remains the same - a celebration of wisdom, heritage, and the strength of community.',
      avatarUrl: 'assets/tx/18001765208768_.pic_hd.jpg',
      worksCount: 3,
      appreciationCount: 3450,
      collections: ['Ancestral Rhythms', 'Proverb Songs'],
      isPro: true,
      location: 'Lagos',
      genre: 'Cultural Poetry',
    ),
    'author10': Author(
      id: 'author10',
      name: 'Oliver Schmidt',
      philosophy: 'Philosophy and poetry are lovers dancing together. Through verse, I explore life\'s big questions with wonder, curiosity, and a touch of humor.',
      avatarUrl: 'assets/tx/18011765208769_.pic_hd.jpg',
      worksCount: 2,
      appreciationCount: 1670,
      collections: ['Philosophical Musings'],
      isPro: false,
      location: 'Berlin',
      genre: 'Philosophical',
    ),
    'author11': Author(
      id: 'author11',
      name: 'Mei Lin',
      philosophy: 'Tea ceremonies and poetry share the same essence: presence. Each word is a sip of eternity, each verse a moment of mindful peace.',
      avatarUrl: 'assets/tx/18021765208770_.pic_hd.jpg',
      worksCount: 3,
      appreciationCount: 2890,
      collections: ['Tea Poems', 'Eternal Sips'],
      isPro: true,
      location: 'Taipei',
      genre: 'Zen Poetry',
    ),
    'author12': Author(
      id: 'author12',
      name: 'Diego Morales',
      philosophy: 'The desert taught me patience and resilience. My poems grow slowly, like cacti under the sun, blooming with unexpected beauty.',
      avatarUrl: 'assets/tx/18031765208771_.pic_hd.jpg',
      worksCount: 2,
      appreciationCount: 1540,
      collections: ['Desert Blooms'],
      isPro: false,
      location: 'Santa Fe',
      genre: 'Desert Poetry',
    ),
    'author13': Author(
      id: 'author13',
      name: 'Freya Andersen',
      philosophy: 'The ocean writes poems on the shore every day, then erases them. I try to remember what I read and share its timeless wisdom.',
      avatarUrl: 'assets/tx/18041765208772_.pic_hd.jpg',
      worksCount: 3,
      appreciationCount: 3670,
      collections: ['Ocean Verses', 'Tidal Memories'],
      isPro: true,
      location: 'Copenhagen',
      genre: 'Maritime Poetry',
    ),
    'author14': Author(
      id: 'author14',
      name: 'Rafael Santos',
      philosophy: 'Music is poetry that forgot to sit down. My words dance with rhythm, celebrating life\'s beautiful, unstoppable energy.',
      avatarUrl: 'assets/tx/18051765208772_.pic_hd.jpg',
      worksCount: 2,
      appreciationCount: 2230,
      collections: ['Dancing Words'],
      isPro: true,
      location: 'Rio de Janeiro',
      genre: 'Musical Poetry',
    ),
    'author15': Author(
      id: 'author15',
      name: 'Zara Khan',
      philosophy: 'In the space between breaths, poems are born. I write in the pauses of life, finding peace in stillness and strength in reflection.',
      avatarUrl: 'assets/tx/18061765208773_.pic_hd.jpg',
      worksCount: 3,
      appreciationCount: 2950,
      collections: ['Between Breaths', 'Life Pauses'],
      isPro: false,
      location: 'Karachi',
      genre: 'Meditative',
    ),
    'author16': Author(
      id: 'author16',
      name: 'Thomas Dubois',
      philosophy: 'Cafés are my cathedrals. I worship at the altar of espresso and observe humanity with compassion, curiosity, and gentle humor.',
      avatarUrl: 'assets/tx/18071765208774_.pic_hd.jpg',
      worksCount: 2,
      appreciationCount: 1780,
      collections: ['Café Chronicles'],
      isPro: false,
      location: 'Paris',
      genre: 'Urban Observer',
    ),
    'author17': Author(
      id: 'author17',
      name: 'Yuki Nakamura',
      philosophy: 'Cherry blossoms fall for only two weeks. My poems try to make those two weeks last forever, celebrating fleeting beauty and eternal hope.',
      avatarUrl: 'assets/tx/18081765208775_.pic_hd.jpg',
      worksCount: 3,
      appreciationCount: 4120,
      collections: ['Sakura Dreams', 'Eternal Spring'],
      isPro: true,
      location: 'Kyoto',
      genre: 'Traditional Japanese',
    ),
    'author18': Author(
      id: 'author18',
      name: 'Hassan Al-Rashid',
      philosophy: 'The stars are ancient poets. I read their verses every night and translate them for the earth, sharing messages of wonder and possibility.',
      avatarUrl: 'assets/tx/18091765208776_.pic_hd.jpg',
      worksCount: 2,
      appreciationCount: 2340,
      collections: ['Star Verses'],
      isPro: true,
      location: 'Dubai',
      genre: 'Celestial Poetry',
    ),
    'author19': Author(
      id: 'author19',
      name: 'Nina Kowalski',
      philosophy: 'Memory is a poet that rewrites history with love. I document these revisions, honoring the past while celebrating the present.',
      avatarUrl: 'assets/tx/18101765208777_.pic_hd.jpg',
      worksCount: 3,
      appreciationCount: 2670,
      collections: ['Memory Revisions', 'History Rewritten'],
      isPro: false,
      location: 'Warsaw',
      genre: 'Memoir Poetry',
    ),
    'author20': Author(
      id: 'author20',
      name: 'Elijah Brooks',
      philosophy: 'Jazz taught me improvisation and joy. My poems are riffs on the theme of existence, celebrating the beautiful spontaneity of life.',
      avatarUrl: 'assets/tx/18111765208777_.pic_hd.jpg',
      worksCount: 2,
      appreciationCount: 3210,
      collections: ['Jazz Riffs', 'Existence Themes'],
      isPro: true,
      location: 'New Orleans',
      genre: 'Jazz Poetry',
    ),
  };

  // 50首积极向上的原创诗歌作品
  static final List<Poem> _allPoems = [
    // Author 1: Emily Whitmore (3 poems)
    Poem(
      id: 'poem1',
      title: 'Dawn\'s First Light',
      content: 'The world awakens softly,\nPainted gold by morning sun.\nBirds compose their symphony,\nA new day has begun.\n\nIn this sacred moment,\nBefore the rush begins,\nI find my center, breathing deep,\nWhere peace and hope begins.',
      authorId: 'author1',
      authorName: 'Emily Whitmore',
      authorAvatarUrl: 'assets/tx/17921765208762_.pic_hd.jpg',
      imageUrl: 'assets/17421765206728_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      likes: 856,
      tags: ['Morning', 'Hope', 'Nature'],
    ),
    Poem(
      id: 'poem2',
      title: 'Library of Dreams',
      content: 'Between worn pages, worlds unfold,\nStories whispered, tales retold.\nEach book a doorway, each word a key,\nUnlocking who we\'re meant to be.\n\nIn quiet corners, magic lives,\nWhere imagination freely gives\nThe gift of flight, the power to see\nBeyond ourselves, to simply be.',
      authorId: 'author1',
      authorName: 'Emily Whitmore',
      authorAvatarUrl: 'assets/tx/17921765208762_.pic_hd.jpg',
      imageUrl: 'assets/17431765206729_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      likes: 723,
      tags: ['Books', 'Imagination', 'Dreams'],
    ),
    Poem(
      id: 'poem3',
      title: 'Rain\'s Gentle Song',
      content: 'Raindrops dance on window glass,\nNature\'s rhythm, soft and slow.\nEach drop a note in Earth\'s great song,\nNourishing all things that grow.\n\nI watch the world wash clean and bright,\nGrateful for this gentle shower,\nReminding me that after storms\nComes beauty, strength, and power.',
      authorId: 'author1',
      authorName: 'Emily Whitmore',
      authorAvatarUrl: 'assets/tx/17921765208762_.pic_hd.jpg',
      imageUrl: 'assets/17441765206730_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      likes: 1024,
      tags: ['Rain', 'Growth', 'Renewal'],
    ),

    // Author 2: Marcus Chen (2 poems)
    Poem(
      id: 'poem4',
      title: 'Building Bridges',
      content: 'Steel and stone span the divide,\nConnecting shores, connecting hearts.\nEvery bridge begins with faith—\nBelief that distance can be crossed.\n\nWe are all bridge builders here,\nReaching out with words and deeds,\nCreating paths where none existed,\nPlanting hope like scattered seeds.',
      authorId: 'author2',
      authorName: 'Marcus Chen',
      authorAvatarUrl: 'assets/tx/17931765208763_.pic_hd.jpg',
      imageUrl: 'assets/17451765206731_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      likes: 945,
      tags: ['Connection', 'Hope', 'Unity'],
    ),
    Poem(
      id: 'poem5',
      title: 'Digital Sunrise',
      content: 'In pixels and in code we write\nOur modern stories, bright and new.\nTechnology connects our world,\nBringing distant hearts in view.\n\nThough screens may separate our hands,\nOur spirits touch across the wire.\nIn every message, every call,\nHumanity\'s eternal fire.',
      authorId: 'author2',
      authorName: 'Marcus Chen',
      authorAvatarUrl: 'assets/tx/17931765208763_.pic_hd.jpg',
      imageUrl: 'assets/17461765206732_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      likes: 1123,
      tags: ['Technology', 'Connection', 'Modern'],
    ),

    // Author 3: Sofia Ramirez (3 poems)
    Poem(
      id: 'poem6',
      title: 'Dance of Life',
      content: 'My heart beats to its own rhythm,\nA dance that\'s wild and free.\nEach step a celebration,\nOf all that I can be.\n\nI spin through joy and laughter,\nI leap through every fear,\nFor life is meant for dancing,\nAnd the music\'s always here.',
      authorId: 'author3',
      authorName: 'Sofia Ramirez',
      authorAvatarUrl: 'assets/tx/17941765208763_.pic_hd.jpg',
      imageUrl: 'assets/17471765206733_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      likes: 1456,
      tags: ['Dance', 'Joy', 'Freedom'],
    ),
    Poem(
      id: 'poem7',
      title: 'Breaking Free',
      content: 'I write my own rules,\nPaint outside the lines,\nSing my own melody,\nCreate my own designs.\n\nLife is too precious\nFor boxes and for walls.\nI choose to soar freely,\nAnswering adventure\'s calls.',
      authorId: 'author3',
      authorName: 'Sofia Ramirez',
      authorAvatarUrl: 'assets/tx/17941765208763_.pic_hd.jpg',
      imageUrl: 'assets/17481765206734_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      likes: 892,
      tags: ['Freedom', 'Courage', 'Individuality'],
    ),
    Poem(
      id: 'poem8',
      title: 'Colors of Expression',
      content: 'Words are my paintbrush,\nEmotions are my hue.\nEach poem is a canvas\nWhere I create anew.\n\nI blend joy with wonder,\nMix courage with delight,\nCreating masterpieces\nThat dance in morning light.',
      authorId: 'author3',
      authorName: 'Sofia Ramirez',
      authorAvatarUrl: 'assets/tx/17941765208763_.pic_hd.jpg',
      imageUrl: 'assets/17491765206735_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      likes: 1678,
      tags: ['Art', 'Expression', 'Creativity'],
    ),

    // Author 4: James O'Connor (2 poems)
    Poem(
      id: 'poem9',
      title: 'Ancient Wisdom',
      content: 'The stones remember everything—\nSeasons turning, years gone by.\nThey teach us patience, teach us strength,\nBeneath the ever-changing sky.\n\nRooted deep in earth and time,\nThey weather every storm with grace.\nReminding us that we too can stand\nFirm and strong in any place.',
      authorId: 'author4',
      authorName: 'James O\'Connor',
      authorAvatarUrl: 'assets/tx/17951765208764_.pic_hd.jpg',
      imageUrl: 'assets/17501765206735_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
      likes: 734,
      tags: ['Wisdom', 'Strength', 'Nature'],
    ),
    Poem(
      id: 'poem10',
      title: 'Wind\'s Message',
      content: 'The wind carries seeds of change,\nWhispering tales of transformation.\nIt bends the trees but breaks them not,\nTeaching flexible adaptation.\n\nListen to its ancient song,\nOf journeys taken, paths unknown.\nEmbrace the change it brings your way—\nIn change, we find how we have grown.',
      authorId: 'author4',
      authorName: 'James O\'Connor',
      authorAvatarUrl: 'assets/tx/17951765208764_.pic_hd.jpg',
      imageUrl: 'assets/17511765206736_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      likes: 891,
      tags: ['Change', 'Growth', 'Adaptation'],
    ),

    // Author 5: Aisha Patel (3 poems)
    Poem(
      id: 'poem11',
      title: 'Monsoon Blessing',
      content: 'First rain arrives—\nThe earth exhales its joy,\nLife begins anew.\n\nPetrichor rises,\nSweet perfume of renewal,\nHope falls from the sky.',
      authorId: 'author5',
      authorName: 'Aisha Patel',
      authorAvatarUrl: 'assets/tx/17961765208765_.pic_hd.jpg',
      imageUrl: 'assets/17521765206737_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(hours: 18)),
      likes: 1234,
      tags: ['Haiku', 'Rain', 'Renewal'],
    ),
    Poem(
      id: 'poem12',
      title: 'Tea and Tranquility',
      content: 'Three leaves unfurl\nIn steaming water—\nA universe blooms.\n\nPatience rewarded,\nFlavor deepens with time,\nPeace in every sip.',
      authorId: 'author5',
      authorName: 'Aisha Patel',
      authorAvatarUrl: 'assets/tx/17961765208765_.pic_hd.jpg',
      imageUrl: 'assets/17531765206738_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      likes: 967,
      tags: ['Tea', 'Peace', 'Mindfulness'],
    ),
    Poem(
      id: 'poem13',
      title: 'Simple Joy',
      content: 'Sunrise.\nSmile.\nKindness.\nLove.\n\nFour words,\nInfinite meaning,\nLife\'s essence,\nPure and true.',
      authorId: 'author5',
      authorName: 'Aisha Patel',
      authorAvatarUrl: 'assets/tx/17961765208765_.pic_hd.jpg',
      imageUrl: 'assets/17541765206739_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 9)),
      likes: 2145,
      tags: ['Joy', 'Minimalist', 'Love'],
    ),

    // Author 6: Lucas Bergström (2 poems)
    Poem(
      id: 'poem14',
      title: 'Winter\'s Gift',
      content: 'Snow blankets the world in white,\nA canvas pure and clean.\nIn winter\'s quiet beauty,\nPeace and clarity are seen.\n\nThe cold teaches us resilience,\nThe ice reflects our strength.\nIn stillness, we find power—\nWinter\'s gift, at length.',
      authorId: 'author6',
      authorName: 'Lucas Bergström',
      authorAvatarUrl: 'assets/tx/17971765208766_.pic_hd.jpg',
      imageUrl: 'assets/17551765206747_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      likes: 823,
      tags: ['Winter', 'Peace', 'Strength'],
    ),
    Poem(
      id: 'poem15',
      title: 'Aurora\'s Dance',
      content: 'Northern lights paint the sky,\nGreen ribbons flowing free.\nNature\'s grand performance,\nA cosmic symphony.\n\nIn awe, I stand beneath\nThis miracle of light,\nReminded that the universe\nIs infinitely bright.',
      authorId: 'author6',
      authorName: 'Lucas Bergström',
      authorAvatarUrl: 'assets/tx/17971765208766_.pic_hd.jpg',
      imageUrl: 'assets/17561765206748_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 11)),
      likes: 1456,
      tags: ['Aurora', 'Wonder', 'Beauty'],
    ),

    // Author 7: Isabella Rossi (3 poems)
    Poem(
      id: 'poem16',
      title: 'Love\'s Journey',
      content: 'Together we ride through life,\nTwo hearts beating as one.\nEvery moment shared with you\nIs a victory won.\n\nThrough ancient streets we wander,\nCreating memories bright.\nOur love story written\nIn laughter and in light.',
      authorId: 'author7',
      authorName: 'Isabella Rossi',
      authorAvatarUrl: 'assets/tx/17981765208767_.pic_hd.jpg',
      imageUrl: 'assets/17571765206749_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      likes: 1789,
      tags: ['Love', 'Partnership', 'Joy'],
    ),
    Poem(
      id: 'poem17',
      title: 'Morning Coffee',
      content: 'Steam rises from my cup,\nCarrying dreams and plans.\nEach sip a small beginning,\nFuture held in my hands.\n\nIn this café corner,\nLife\'s possibilities unfold.\nEvery day\'s a new chapter,\nEvery story yet untold.',
      authorId: 'author7',
      authorName: 'Isabella Rossi',
      authorAvatarUrl: 'assets/tx/17981765208767_.pic_hd.jpg',
      imageUrl: 'assets/17581765206750_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      likes: 2134,
      tags: ['Morning', 'Hope', 'New Beginnings'],
    ),
    Poem(
      id: 'poem18',
      title: 'Fountain of Wishes',
      content: 'I throw three coins of hope,\nInto waters clear and deep.\nOne for dreams already lived,\nOne for promises to keep.\n\nThe third for future blessings,\nFor love that\'s yet to bloom.\nThe fountain holds my wishes,\nDispelling any gloom.',
      authorId: 'author7',
      authorName: 'Isabella Rossi',
      authorAvatarUrl: 'assets/tx/17981765208767_.pic_hd.jpg',
      imageUrl: 'assets/17591765206751_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      likes: 1923,
      tags: ['Hope', 'Dreams', 'Future'],
    ),

    // Author 8: Kenji Tanaka (2 poems)
    Poem(
      id: 'poem19',
      title: 'City Heartbeat',
      content: 'A thousand souls converge,\nEach with their own bright story.\nFor one brief moment, we share\nThis space, this urban glory.\n\nIn the crossing, we connect—\nStrangers yet somehow the same.\nAll seeking purpose, seeking joy,\nAll playing life\'s great game.',
      authorId: 'author8',
      authorName: 'Kenji Tanaka',
      authorAvatarUrl: 'assets/tx/17991765208768_.pic_hd.jpg',
      imageUrl: 'assets/17601765206752_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      likes: 1567,
      tags: ['City', 'Connection', 'Community'],
    ),
    Poem(
      id: 'poem20',
      title: 'Neon Dreams',
      content: 'City lights glow warm at night,\nGuiding wanderers home.\nIn every lit window,\nStories yet unknown.\n\nThe urban landscape pulses\nWith energy and life.\nBeauty in the chaos,\nHarmony in strife.',
      authorId: 'author8',
      authorName: 'Kenji Tanaka',
      authorAvatarUrl: 'assets/tx/17991765208768_.pic_hd.jpg',
      imageUrl: 'assets/17611765206753_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      likes: 1234,
      tags: ['Night', 'City', 'Beauty'],
    ),

    // Author 9: Amara Okafor (3 poems)
    Poem(
      id: 'poem21',
      title: 'Ancestral Wisdom',
      content: 'My grandmother\'s words\nWere seeds planted deep.\nYears later they bloom\nIn lessons that I keep.\n\nHer wisdom flows through me,\nA river strong and true.\nConnecting past to present,\nOld wisdom made anew.',
      authorId: 'author9',
      authorName: 'Amara Okafor',
      authorAvatarUrl: 'assets/tx/18001765208768_.pic_hd.jpg',
      imageUrl: 'assets/17621765206754_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(hours: 20)),
      likes: 1678,
      tags: ['Heritage', 'Wisdom', 'Family'],
    ),
    Poem(
      id: 'poem22',
      title: 'Rhythm of Unity',
      content: 'The drum speaks truth\nIn language universal.\nRhythm connects all hearts,\nMaking joy dispersal.\n\nWe dance together,\nBound by ancient beat.\nCelebrating life and love,\nMaking circle complete.',
      authorId: 'author9',
      authorName: 'Amara Okafor',
      authorAvatarUrl: 'assets/tx/18001765208768_.pic_hd.jpg',
      imageUrl: 'assets/17631765206755_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      likes: 1445,
      tags: ['Music', 'Unity', 'Celebration'],
    ),
    Poem(
      id: 'poem23',
      title: 'Stories in the Wind',
      content: 'The wind carries tales\nOf courage and of grace,\nOf ancestors who paved the way,\nWho ran this earthly race.\n\nTheir strength lives on in us,\nTheir dreams we carry forward.\nBuilding on their legacy,\nToward futures bright and toward.',
      authorId: 'author9',
      authorName: 'Amara Okafor',
      authorAvatarUrl: 'assets/tx/18001765208768_.pic_hd.jpg',
      imageUrl: 'assets/17641765206756_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      likes: 1889,
      tags: ['Heritage', 'Strength', 'Legacy'],
    ),

    // Author 10: Oliver Schmidt (2 poems)
    Poem(
      id: 'poem24',
      title: 'Daily Rituals',
      content: 'In routine, I find my peace,\nEach day a structured dance.\nConsistency brings clarity,\nGiving chaos not a chance.\n\nThrough mindful repetition,\nI discover who I am.\nIn the ordinary moments,\nLife\'s extraordinary plan.',
      authorId: 'author10',
      authorName: 'Oliver Schmidt',
      authorAvatarUrl: 'assets/tx/18011765208769_.pic_hd.jpg',
      imageUrl: 'assets/17651765206757_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      likes: 923,
      tags: ['Mindfulness', 'Peace', 'Routine'],
    ),
    Poem(
      id: 'poem25',
      title: 'Life\'s Flavor',
      content: 'Philosophy and coffee blend—\nBoth bitter, both profound.\nBoth wake us to reality,\nBoth help truth to be found.\n\nI sip and contemplate\nThe sweetness life can bring.\nWith gratitude and wonder,\nI embrace everything.',
      authorId: 'author10',
      authorName: 'Oliver Schmidt',
      authorAvatarUrl: 'assets/tx/18011765208769_.pic_hd.jpg',
      imageUrl: 'assets/17661765206759_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 9)),
      likes: 1345,
      tags: ['Gratitude', 'Philosophy', 'Joy'],
    ),

    // Author 11: Mei Lin (3 poems)
    Poem(
      id: 'poem26',
      title: 'Tea Wisdom',
      content: 'In the bottom of the cup,\nLeaves tell stories true.\nPatience brings its rewards,\nIn all we say and do.\n\nThe art of tea reminds us:\nGood things take their time.\nRushing ruins flavor—\nPatience is sublime.',
      authorId: 'author11',
      authorName: 'Mei Lin',
      authorAvatarUrl: 'assets/tx/18021765208770_.pic_hd.jpg',
      imageUrl: 'assets/17671765206760_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(hours: 15)),
      likes: 1456,
      tags: ['Tea', 'Patience', 'Wisdom'],
    ),
    Poem(
      id: 'poem27',
      title: 'Bamboo Strength',
      content: 'Bamboo bends but never breaks,\nFlexible yet strong.\nRooted deep, it sways with wind,\nSurviving all along.\n\nLike bamboo, we too can bend\nWithout losing our core.\nAdapting to life\'s changes,\nGrowing ever more.',
      authorId: 'author11',
      authorName: 'Mei Lin',
      authorAvatarUrl: 'assets/tx/18021765208770_.pic_hd.jpg',
      imageUrl: 'assets/17681765206761_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      likes: 1678,
      tags: ['Strength', 'Flexibility', 'Growth'],
    ),
    Poem(
      id: 'poem28',
      title: 'Ink and Intention',
      content: 'Grinding ink on stone,\nCircular motion of mindfulness.\nEach stroke deliberate,\nEach word intentional.\n\nThe poem writes itself\nWhen heart and hand align.\nIn presence, art emerges—\nPure and true and fine.',
      authorId: 'author11',
      authorName: 'Mei Lin',
      authorAvatarUrl: 'assets/tx/18021765208770_.pic_hd.jpg',
      imageUrl: 'assets/17691765206762_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
      likes: 1234,
      tags: ['Art', 'Mindfulness', 'Intention'],
    ),

    // Author 12: Diego Morales (2 poems)
    Poem(
      id: 'poem29',
      title: 'Desert Resilience',
      content: 'After patient waiting,\nThe desert bursts with bloom.\nCacti flowers prove that beauty\nCan emerge from any gloom.\n\nResilience is the lesson\nThe desert teaches best:\nEndure, adapt, and flourish—\nPass every single test.',
      authorId: 'author12',
      authorName: 'Diego Morales',
      authorAvatarUrl: 'assets/tx/18031765208771_.pic_hd.jpg',
      imageUrl: 'assets/17701765206763_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      likes: 1123,
      tags: ['Resilience', 'Hope', 'Beauty'],
    ),
    Poem(
      id: 'poem30',
      title: 'Earth\'s Embrace',
      content: 'Adobe walls breathe with the earth,\nCool in heat, warm in cold.\nBuilt from mud and straw and sun,\nStories centuries old.\n\nWe too are made of earth,\nConnected to this land.\nIn harmony with nature,\nTogether we can stand.',
      authorId: 'author12',
      authorName: 'Diego Morales',
      authorAvatarUrl: 'assets/tx/18031765208771_.pic_hd.jpg',
      imageUrl: 'assets/17711765206764_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      likes: 867,
      tags: ['Nature', 'Harmony', 'Connection'],
    ),

    // Author 13: Freya Andersen (3 poems)
    Poem(
      id: 'poem31',
      title: 'Guiding Light',
      content: 'Every night I light the lamp,\nA beacon in the dark.\nGuiding travelers safely home,\nIgniting hope\'s bright spark.\n\nWe all can be a lighthouse,\nShining for those in need.\nOffering light and guidance,\nPlanting kindness\' seed.',
      authorId: 'author13',
      authorName: 'Freya Andersen',
      authorAvatarUrl: 'assets/tx/18041765208772_.pic_hd.jpg',
      imageUrl: 'assets/17721765206764_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
      likes: 1789,
      tags: ['Hope', 'Kindness', 'Purpose'],
    ),
    Poem(
      id: 'poem32',
      title: 'Tide Pool Wonders',
      content: 'Small worlds left by the tide,\nTeeming with vibrant life.\nAnemones and starfish wait\nThrough temporary strife.\n\nPatience is their virtue,\nTrust their guiding star.\nThe ocean will return to them—\nThey know just who they are.',
      authorId: 'author13',
      authorName: 'Freya Andersen',
      authorAvatarUrl: 'assets/tx/18041765208772_.pic_hd.jpg',
      imageUrl: 'assets/17731765206765_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      likes: 1456,
      tags: ['Patience', 'Trust', 'Nature'],
    ),
    Poem(
      id: 'poem33',
      title: 'Bonds That Hold',
      content: 'My grandfather taught me\nTo tie knots strong and true.\nEach loop a promise kept,\nEach twist a bond renewed.\n\nLove is like these sailor knots—\nTested by the storm.\nBut tied with care and patience,\nIt keeps our hearts warm.',
      authorId: 'author13',
      authorName: 'Freya Andersen',
      authorAvatarUrl: 'assets/tx/18041765208772_.pic_hd.jpg',
      imageUrl: 'assets/17741765206766_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      likes: 1923,
      tags: ['Family', 'Love', 'Tradition'],
    ),

    // Author 14: Rafael Santos (2 poems)
    Poem(
      id: 'poem34',
      title: 'Rhythm of Joy',
      content: 'The city moves to samba,\nEven heartbeats keep the time.\nLife is meant for dancing,\nEvery moment is sublime.\n\nI don\'t just walk through life—\nI dance with every step.\nFinding rhythm in the chaos,\nKeeping joy and pep.',
      authorId: 'author14',
      authorName: 'Rafael Santos',
      authorAvatarUrl: 'assets/tx/18051765208772_.pic_hd.jpg',
      imageUrl: 'assets/17751765206767_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      likes: 1567,
      tags: ['Dance', 'Joy', 'Celebration'],
    ),
    Poem(
      id: 'poem35',
      title: 'Festival of Life',
      content: 'For days we celebrate,\nShedding worry, embracing play.\nConfetti falls like blessings,\nWashing cares away.\n\nLife itself\'s a carnival—\nColorful and bright.\nEvery day\'s a festival\nIf we see it right.',
      authorId: 'author14',
      authorName: 'Rafael Santos',
      authorAvatarUrl: 'assets/tx/18051765208772_.pic_hd.jpg',
      imageUrl: 'assets/17761765206768_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
      likes: 1834,
      tags: ['Celebration', 'Joy', 'Life'],
    ),

    // Author 15: Zara Khan (3 poems)
    Poem(
      id: 'poem36',
      title: 'Sacred Moments',
      content: 'In quiet contemplation,\nI count my blessings one by one.\nEach breath a gift of gratitude,\nEach moment, peace begun.\n\nThe hundredth name is silence—\nWhere all answers dwell.\nIn stillness, truth emerges,\nMore than words can tell.',
      authorId: 'author15',
      authorName: 'Zara Khan',
      authorAvatarUrl: 'assets/tx/18061765208773_.pic_hd.jpg',
      imageUrl: 'assets/17771765206769_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(hours: 10)),
      likes: 1345,
      tags: ['Peace', 'Gratitude', 'Spirituality'],
    ),
    Poem(
      id: 'poem37',
      title: 'Rain\'s Blessing',
      content: 'The first drops fall like grace,\nThe earth sighs with relief.\nChildren dance in puddles—\nPure joy beyond belief.\n\nRain washes all things clean,\nBringing life and growth.\nA blessing from the heavens,\nFulfilling nature\'s oath.',
      authorId: 'author15',
      authorName: 'Zara Khan',
      authorAvatarUrl: 'assets/tx/18061765208773_.pic_hd.jpg',
      imageUrl: 'assets/17781765206770_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      likes: 1678,
      tags: ['Rain', 'Joy', 'Blessing'],
    ),
    Poem(
      id: 'poem38',
      title: 'Art of Impermanence',
      content: 'She draws on my hands\nTemporary beauty,\nEach swirl a blessing,\nFading gracefully.\n\nThis teaches us:\nNothing lasts forever.\nCherish every moment,\nLet go with grace, never sever.',
      authorId: 'author15',
      authorName: 'Zara Khan',
      authorAvatarUrl: 'assets/tx/18061765208773_.pic_hd.jpg',
      imageUrl: 'assets/17791765206771_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      likes: 1456,
      tags: ['Art', 'Impermanence', 'Wisdom'],
    ),

    // Author 16: Thomas Dubois (2 poems)
    Poem(
      id: 'poem39',
      title: 'Café Observations',
      content: 'I watch humanity unfold\nThrough rising coffee steam.\nEach person carries stories,\nEach life a unique dream.\n\nIn this café sanctuary,\nWe\'re all connected here.\nSharing space and moments,\nBringing distant hearts near.',
      authorId: 'author16',
      authorName: 'Thomas Dubois',
      authorAvatarUrl: 'assets/tx/18071765208774_.pic_hd.jpg',
      imageUrl: 'assets/17801765206772_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      likes: 1234,
      tags: ['Community', 'Connection', 'Observation'],
    ),
    Poem(
      id: 'poem40',
      title: 'Simple Pleasures',
      content: 'Flaky pastry, morning light,\nCrumbs scattered on the table.\nSimple joys remind us\nThat happiness is stable.\n\nNot in grand gestures found,\nBut in small delights each day.\nGratitude for little things\nLights our entire way.',
      authorId: 'author16',
      authorName: 'Thomas Dubois',
      authorAvatarUrl: 'assets/tx/18071765208774_.pic_hd.jpg',
      imageUrl: 'assets/17811765206772_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      likes: 967,
      tags: ['Gratitude', 'Joy', 'Simple Pleasures'],
    ),

    // Author 17: Yuki Nakamura (3 poems)
    Poem(
      id: 'poem41',
      title: 'Sakura Season',
      content: 'Petals drift like snow,\nEach one a gentle goodbye.\nBeauty\'s brief moment—\n\nYet in their falling,\nCherry blossoms teach us grace:\nEndings can be lovely.',
      authorId: 'author17',
      authorName: 'Yuki Nakamura',
      authorAvatarUrl: 'assets/tx/18081765208775_.pic_hd.jpg',
      imageUrl: 'assets/17821765206773_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      likes: 2345,
      tags: ['Sakura', 'Grace', 'Beauty'],
    ),
    Poem(
      id: 'poem42',
      title: 'Temple Peace',
      content: 'One hundred eight rings,\nEach bell tone carries away\nWorries and burdens.\n\nThe sound fades slowly,\nLeaving only clarity—\nSilence speaks loudest.',
      authorId: 'author17',
      authorName: 'Yuki Nakamura',
      authorAvatarUrl: 'assets/tx/18081765208775_.pic_hd.jpg',
      imageUrl: 'assets/17831765206774_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      likes: 1890,
      tags: ['Peace', 'Temple', 'Clarity'],
    ),
    Poem(
      id: 'poem43',
      title: 'Koi Reflection',
      content: 'Orange and white circles,\nSwimming through sky\'s reflection.\nHeaven meets earth here.\n\nIn the pond\'s mirror,\nTwo worlds become one—\nBeauty doubled, peace profound.',
      authorId: 'author17',
      authorName: 'Yuki Nakamura',
      authorAvatarUrl: 'assets/tx/18081765208775_.pic_hd.jpg',
      imageUrl: 'assets/17841765206775_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 9)),
      likes: 1678,
      tags: ['Nature', 'Reflection', 'Harmony'],
    ),

    // Author 18: Hassan Al-Rashid (2 poems)
    Poem(
      id: 'poem44',
      title: 'Starlit Wonder',
      content: 'In the desert, stars multiply,\nNo city lights compete.\nThe Milky Way spills across darkness,\nMaking wonder complete.\n\nI am small beneath infinity,\nYet somehow that feels right.\nConnected to the cosmos,\nPart of endless light.',
      authorId: 'author18',
      authorName: 'Hassan Al-Rashid',
      authorAvatarUrl: 'assets/tx/18091765208776_.pic_hd.jpg',
      imageUrl: 'assets/17851765206776_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      likes: 1789,
      tags: ['Stars', 'Wonder', 'Universe'],
    ),
    Poem(
      id: 'poem45',
      title: 'Celestial Stories',
      content: 'My ancestors named the stars,\nConnected dots into myths.\nI trace the same patterns,\nAdding my own gifts.\n\nThe sky is our shared canvas,\nPainted with dreams and light.\nEach generation adds beauty,\nMaking the future bright.',
      authorId: 'author18',
      authorName: 'Hassan Al-Rashid',
      authorAvatarUrl: 'assets/tx/18091765208776_.pic_hd.jpg',
      imageUrl: 'assets/17861765206777_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      likes: 1567,
      tags: ['Heritage', 'Dreams', 'Legacy'],
    ),

    // Author 19: Nina Kowalski (3 poems)
    Poem(
      id: 'poem46',
      title: 'Recipe for Love',
      content: 'She never wrote it down,\nMeasurements in handfuls.\nYet every dish she made\nWas filled with love and care.\n\nNow I cook from memory,\nTasting her in every bite.\nHer love lives on through recipes,\nMaking everything right.',
      authorId: 'author19',
      authorName: 'Nina Kowalski',
      authorAvatarUrl: 'assets/tx/18101765208777_.pic_hd.jpg',
      imageUrl: 'assets/17871765206778_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(hours: 14)),
      likes: 1456,
      tags: ['Family', 'Love', 'Memory'],
    ),
    Poem(
      id: 'poem47',
      title: 'Faces of Heritage',
      content: 'Faces I never met,\nYet I recognize their eyes.\nGenetic memory flows,\nConnecting earth to skies.\n\nThe past lives in my features,\nTheir strength flows in my veins.\nI am their continuation,\nTheir love forever remains.',
      authorId: 'author19',
      authorName: 'Nina Kowalski',
      authorAvatarUrl: 'assets/tx/18101765208777_.pic_hd.jpg',
      imageUrl: 'assets/17881765206779_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      likes: 1678,
      tags: ['Heritage', 'Identity', 'Strength'],
    ),
    Poem(
      id: 'poem48',
      title: 'City Reborn',
      content: 'They rebuilt the old town,\nBrick by brick from memory.\nA city that refused to forget,\nRising with dignity.\n\nProof that what we love\nWe can resurrect and renew.\nHope is stronger than destruction,\nLove will see us through.',
      authorId: 'author19',
      authorName: 'Nina Kowalski',
      authorAvatarUrl: 'assets/tx/18101765208777_.pic_hd.jpg',
      imageUrl: 'assets/17891765206780_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      likes: 1923,
      tags: ['Hope', 'Resilience', 'Renewal'],
    ),

    // Author 20: Elijah Brooks (2 poems)
    Poem(
      id: 'poem49',
      title: 'Jazz Spirit',
      content: 'The saxophone sings,\nImproving on life\'s melody.\nEach note unrehearsed,\nYet perfectly placed.\n\nLife is like jazz—\nBeautiful because it\'s unplanned.\nEmbrace the improvisation,\nLet your spirit expand.',
      authorId: 'author20',
      authorName: 'Elijah Brooks',
      authorAvatarUrl: 'assets/tx/18111765208777_.pic_hd.jpg',
      imageUrl: 'assets/17901765206781_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      likes: 1834,
      tags: ['Jazz', 'Freedom', 'Life'],
    ),
    Poem(
      id: 'poem50',
      title: 'Renewal Rain',
      content: 'Rain on cobblestones,\nWashing the city clean.\nEvery drop a fresh start,\nEvery storm a new scene.\n\nNew Orleans knows renewal,\nRising after every rain.\nProof that we can start again,\nTransforming joy from pain.',
      authorId: 'author20',
      authorName: 'Elijah Brooks',
      authorAvatarUrl: 'assets/tx/18111765208777_.pic_hd.jpg',
      imageUrl: 'assets/17911765206782_.pic_hd.jpg',
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
      likes: 1567,
      tags: ['Renewal', 'Hope', 'Resilience'],
    ),
  ];

  // 获取所有诗歌（用于Discovery页面，每位作者只显示一首）
  static List<Poem> getMockPoems() {
    // 为每位作者选择第一首诗歌
    final Map<String, Poem> authorFirstPoems = {};
    for (var poem in _allPoems) {
      if (!authorFirstPoems.containsKey(poem.authorId)) {
        authorFirstPoems[poem.authorId] = poem;
      }
    }
    return authorFirstPoems.values.toList()
      ..sort((a, b) => b.createdAt.compareTo(a.createdAt));
  }

  // 获取作者信息
  static Author getMockAuthor(String authorId) {
    return _authors[authorId] ?? _authors['author1']!;
  }

  // 获取作者的所有作品
  static List<Poem> getAuthorWorks(String authorId) {
    return _allPoems.where((p) => p.authorId == authorId).toList()
      ..sort((a, b) => b.createdAt.compareTo(a.createdAt));
  }

  // 获取所有作者
  static List<Author> getAllAuthors() {
    return _authors.values.toList();
  }

  // 根据ID获取诗歌
  static Poem? getPoemById(String poemId) {
    try {
      return _allPoems.firstWhere((p) => p.id == poemId);
    } catch (e) {
      return null;
    }
  }
}
