class DropoutNumericalLoopPool {
  final String itemId;
  final String name;
  final String type;
  final int coinAmount;
  final String price;
  final String description;
  final String locale;
  final String category;
  final bool isLimited;

  const DropoutNumericalLoopPool({
    required this.itemId,
    required this.name,
    required this.type,
    required this.coinAmount,
    required this.price,
    required this.description,
    required this.locale,
    required this.category,
    this.isLimited = false,
  });
}

const List<DropoutNumericalLoopPool> shopInventory = <DropoutNumericalLoopPool>[
  // Regular Packages
  DropoutNumericalLoopPool(
    itemId: '5313001',
    name: '98 Coins',
    type: 'consumable',
    coinAmount: 98,
    price: '\$0.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'basic',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313002',
    name: '198 Coins',
    type: 'consumable',
    coinAmount: 198,
    price: '\$1.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'basic',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313003',
    name: '298 Coins',
    type: 'consumable',
    coinAmount: 298,
    price: '\$2.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'basic',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313004',
    name: '398 Coins',
    type: 'consumable',
    coinAmount: 398,
    price: '\$3.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'basic',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313005',
    name: '498 Coins',
    type: 'consumable',
    coinAmount: 498,
    price: '\$4.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'basic',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313006',
    name: '598 Coins',
    type: 'consumable',
    coinAmount: 598,
    price: '\$5.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'basic',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313007',
    name: '698 Coins',
    type: 'consumable',
    coinAmount: 698,
    price: '\$6.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'basic',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313008',
    name: '798 Coins',
    type: 'consumable',
    coinAmount: 798,
    price: '\$7.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'basic',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313009',
    name: '898 Coins',
    type: 'consumable',
    coinAmount: 898,
    price: '\$8.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'basic',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313010',
    name: '1198 Coins',
    type: 'consumable',
    coinAmount: 1198,
    price: '\$9.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'popular',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313011',
    name: '1298 Coins',
    type: 'consumable',
    coinAmount: 1298,
    price: '\$12.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'popular',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313012',
    name: '2498 Coins',
    type: 'consumable',
    coinAmount: 2498,
    price: '\$19.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'popular',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313013',
    name: '6998 Coins',
    type: 'consumable',
    coinAmount: 6998,
    price: '\$49.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'premium',
  ),
  DropoutNumericalLoopPool(
    itemId: '5313014',
    name: '14998 Coins',
    type: 'consumable',
    coinAmount: 14998,
    price: '\$99.99',
    description: 'Recharge Get Coins',
    locale: 'en_US',
    category: 'premium',
  ),
  
  // Limited Offers
  DropoutNumericalLoopPool(
    itemId: '5313015',
    name: '498 Coins',
    type: 'consumable',
    coinAmount: 498,
    price: '\$1.99',
    description: 'Limited Recharge Get Coins',
    locale: 'en_US',
    category: 'limited',
    isLimited: true,
  ),
  DropoutNumericalLoopPool(
    itemId: '5313016',
    name: '748 Coins',
    type: 'consumable',
    coinAmount: 748,
    price: '\$2.99',
    description: 'Limited Recharge Get Coins',
    locale: 'en_US',
    category: 'limited',
    isLimited: true,
  ),
  DropoutNumericalLoopPool(
    itemId: '5313017',
    name: '1198 Coins',
    type: 'consumable',
    coinAmount: 1198,
    price: '\$4.99',
    description: 'Limited Recharge Get Coins',
    locale: 'en_US',
    category: 'limited',
    isLimited: true,
  ),
  DropoutNumericalLoopPool(
    itemId: '5313018',
    name: '1398 Coins',
    type: 'consumable',
    coinAmount: 1398,
    price: '\$5.99',
    description: 'Limited Recharge Get Coins',
    locale: 'en_US',
    category: 'limited',
    isLimited: true,
  ),
  DropoutNumericalLoopPool(
    itemId: '5313019',
    name: '2498 Coins',
    type: 'consumable',
    coinAmount: 2498,
    price: '\$11.99',
    description: 'Limited Recharge Get Coins',
    locale: 'en_US',
    category: 'limited',
    isLimited: true,
  ),
  DropoutNumericalLoopPool(
    itemId: '5313020',
    name: '2598 Coins',
    type: 'consumable',
    coinAmount: 2598,
    price: '\$12.99',
    description: 'Limited Recharge Get Coins',
    locale: 'en_US',
    category: 'limited',
    isLimited: true,
  ),
  DropoutNumericalLoopPool(
    itemId: '5313021',
    name: '6998 Coins',
    type: 'consumable',
    coinAmount: 6998,
    price: '\$34.99',
    description: 'Limited Recharge Get Coins',
    locale: 'en_US',
    category: 'limited',
    isLimited: true,
  ),
  DropoutNumericalLoopPool(
    itemId: '5313022',
    name: '14998 Coins',
    type: 'consumable',
    coinAmount: 14998,
    price: '\$79.99',
    description: 'Limited Recharge Get Coins',
    locale: 'en_US',
    category: 'limited',
    isLimited: true,
  ),
];
