import 'package:flutter/material.dart';
import 'package:orivet/core/constants/colors.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class SpecialInstructionsScreen extends StatelessWidget {
  const SpecialInstructionsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.vellum,
      appBar: AppBar(
        title: Text("Special Instructions",
            style: Theme.of(context)
                .textTheme
                .displaySmall
                ?.copyWith(fontSize: 20)),
        backgroundColor: AppColors.vellum,
        elevation: 0,
        leading: IconButton(
          icon:
              const Icon(FontAwesomeIcons.arrowLeft, color: AppColors.leather),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: AppColors.wax.withOpacity(0.1),
                border: Border.all(color: AppColors.wax),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                children: [
                  const Icon(FontAwesomeIcons.triangleExclamation,
                      color: AppColors.wax),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Text(
                      "READ CAREFULLY BEFORE STARTING ANY RESTORATION",
                      style: Theme.of(context).textTheme.labelSmall?.copyWith(
                          color: AppColors.wax, fontWeight: FontWeight.bold),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),
            _buildSection(
              "AI Accuracy",
              "Restoration plans are generated by AI. While we strive for high accuracy, the AI may misidentify rare materials or subtle conditions. Always verify with your own judgment.",
              FontAwesomeIcons.robot,
            ),
            _buildSection(
              "Professional Advice",
              "For valuable, rare, or highly fragile artifacts, DO NOT rely solely on this app. We strongly recommend consulting with a certified professional conservator.",
              FontAwesomeIcons.userTie,
            ),
            _buildSection(
              "Chemical Safety",
              "Some guides may suggest cleaning agents. Always work in a well-ventilated area. Never mix chemicals unless explicitly instructed and safe to do so.",
              FontAwesomeIcons.flask,
            ),
            _buildSection(
              "Protective Gear",
              "Always wear appropriate protective gear (gloves, masks, protective eyewear) when handling chemicals, dust, or sharp fragments.",
              FontAwesomeIcons.shieldHalved,
            ),
            _buildSection(
              "Handling Fragile Items",
              "Handle artifacts as little as possible. Support them from the base. Use padded surfaces to prevent accidental damage during examination.",
              FontAwesomeIcons.handHoldingMedical,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSection(String title, String content, IconData icon) {
    return Container(
      margin: const EdgeInsets.only(bottom: 24),
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.6),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: AppColors.leather.withOpacity(0.15)),
        boxShadow: [
          BoxShadow(
            color: AppColors.leather.withOpacity(0.05),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: AppColors.shale,
              shape: BoxShape.circle,
            ),
            child: Icon(icon, color: AppColors.leather, size: 20),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title,
                    style: const TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                        color: AppColors.leather)),
                const SizedBox(height: 8),
                Text(content,
                    style: const TextStyle(
                        fontSize: 14, color: AppColors.ink, height: 1.5)),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
