class Announcements {
  static const List<String> list = [
    "A rare 1920s steam-powered calculating machine has been unearthed in London.",
    "New restoration techniques for brass oxidation discovered by our artisan guild.",
    "The Annual Steampunk Inventors Fair will be held next month in the virtual plaza.",
    "Lost blueprints of a Victorian airship found in an old library archive.",
    "An anonymous collector is seeking information on 'The Chronos Key'.",
    "Restoration workshop: Learn how to polish antique copper without damage.",
    "Mystery artifact #402 identified as a prototype telegraph encoder.",
    "Reminder: Keep your mechanical gears oiled to prevent rust during the rainy season.",
    "A cache of 50 vintage fountain pens from the 1930s has been cataloged.",
    "The 'Clockwork Heart' exhibit is now open for virtual touring.",
    "Warning: Counterfeit vacuum tubes are circulating in the market.",
    "Interview with a master horologist: 'Time is but a construct of gears'.",
    "New arrival: A pristine set of surveyor's tools from the 1880s.",
    "Did you know? Early daguerreotypes require specific humidity for preservation.",
    "Community challenge: Share your best 'Before & After' restoration photos.",
    "A secret compartment was found in the 'Navigator's Desk' artifact.",
    "Update on the 'Silver Pocket Watch' series: Production year revised to 1895.",
    "Looking for spare parts? Check the new 'Salvage Yard' section.",
    "The mystery of the 'Singing Music Box' has finally been solved.",
    "Upcoming webinar: 'The Art of Leather Reconditioning' this Sunday.",
    "Rare 'Zeppelin' style goggles added to the public archive.",
    "Notice: The archive server will undergo maintenance to polish the digital gears.",
    "A diary from a WWI aviator has been donated to the oral history project.",
    "Discover the history behind the 'Phantom Lens' camera series.",
    "Tip: Use beeswax to protect your wooden artifacts from cracking.",
    "The 'Alchemist's Scale' is now marked as 'Restored' in the gallery.",
    "Seeking: Brass screws size 2mm for a delicate music box repair.",
    "New theory proposes that artifact #892 was used for celestial navigation.",
    "Join the discussion on 'The Ethics of Modernizing Antique Tech'.",
    "Congratulations to User 'GearHead' for completing 100 restorations!"
  ];
}
